---
title: "Ejection and Sweep Analysis other figures"
subtitle: "Experiments in canopy flux (Yukio Inoue)"
author: "Greg Nishihara"
institute: "Organization for Marine Science and Technology"
date: "2019 January 05"
output: 
  bookdown::pdf_document2:
    keep_tex: yes
    fig_caption: yes
    highlight: tango
    includes:
      in_header : ~/.latex_preambles/preamble.tex
    latex_engine: xelatex
    extra_dependencies: subfig
fontsize: 10pt
geometry: a4paper
lot: yes
lof: yes
link-citations: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# knitr::opts_knit$set(eval.after = 'fig.cap')
knitr::opts_chunk$set(cache = TRUE,
                      echo = FALSE,
                      out.width = "95%", 
                      fig.align = "center", 
                      fig.height = 6, 
                      fig.width  = 6,
                      warning = FALSE, error = FALSE, autodep = TRUE,
                      dev = 'CairoPDF')
options(texi2dvi = "xetex")
options(kableExtra.latex.load_packages = FALSE, tidyverse.quiet = TRUE)
set.seed(2019)
# source("r-setup.R")
```

\pagebreak


```{r library, message = FALSE, warning = FALSE, cache = FALSE}
library(tidyverse, quietly = TRUE)
library(broom, quietly = TRUE)
library(modelr, quietly = TRUE)
library(glue, quietly = TRUE)
library(lemon, quietly = TRUE)
library(knitr, quietly = TRUE)
library(kableExtra, quietly = TRUE)
library(gridExtra, quietly = TRUE)
library(grid, quietly = TRUE)
library(gtable, quietly = TRUE)
library(stringr, quietly = TRUE)
library(Cairo, quietly = TRUE)
set.seed(2019)
options(mc.cores = 4)
```

```{r}
calculate_TKE = function(up, vp, wp) {
  0.5*(up*up + vp*vp + wp*wp)
}
calculate_stress = function(up, wp) {
  abs(up * wp)
}
calculate_mean_stress = function(X) {
  X %>% 
    summarise(mean_stress = mean(calculate_stress(up, wp))) %>% 
    pull(mean_stress)
}
calculate_mean_tke = function(X) {
  X %>% 
    mutate(out = calculate_TKE(up, vp, wp)) %>% 
    summarise(mean_tke = mean(out)) %>% 
    pull(mean_tke)
}

calculate_mean_velocity = function(X) {
  # using rowSums is faster than using
  # rowwise() %> %mutate(a  = sum(w, w2, na.rm=TRUE)) 
  X %>% 
    mutate(a  = rowSums(cbind(w, w2), na.rm=TRUE)) %>% 
    select(u, v, w=a) %>% 
    summarise_all(funs(mean = mean, sd = sd))
}

calculate_total_time = function(X) {
  # In seconds
  X %>% 
    summarise(total_time = length(up) * 0.005) %>% 
    pull(total_time)
}

identify_quadrant = function(up, wp) {
  case_when(
    (wp > 0 & up > 0) ~ 1,
    (wp > 0 & up < 0) ~ 2,
    (wp < 0 & up < 0) ~ 3,
    (wp < 0 & up > 0) ~ 4
  )
}

quadrant_analysis_function = function(H) {
  function(X) {
    N = nrow(X)
    mean_stress = 
      X %>% mutate(stress = calculate_stress(up,wp)) %>% 
      summarise(mean_stress = mean(stress)) %>% 
      pull(mean_stress)
    X %>% 
      mutate(hole_size = rep(H, N)) %>% 
      mutate(Stress = calculate_stress(up, wp)) %>% 
      mutate(in_hole = abs(Stress) /
               abs(mean_stress) <= H) %>% 
      mutate(Quadrant = 
               identify_quadrant(up, wp))
  }
}

calculate_residuals = function(X) {
  X %>% 
    mutate(a  = rowSums(cbind(w, w2), na.rm=TRUE)) %>% 
    mutate_at(vars(u, v, a), function(x) {
      z = mean(x, na.rm=T)
      x - z
    }) %>%
    rename(up = u, vp = v, wp = a) %>% 
    ungroup()
}

run_analysis = function(x) {
  x %>% 
    ungroup() %>% 
    mutate(Position = 
             case_when((Depth > 13) ~ 1,
                       (Depth >= 7 & 
                          Depth <= 13) ~ 2,
                       (Depth < 7) ~ 3)) %>%
    mutate(Position = 
             factor(Position,
                    labels = c("Above canopy",
                               "Canopy edge",
                               "Within canopy"),
                    order = TRUE)) %>%
    mutate(Density = 
             factor(Density,
                    levels = c("H", "M", "L"),
                    labels = c("High",
                               "Medium",
                               "Low"),
                    order = TRUE)) %>%
    mutate(Hz = ifelse(Hz == 5, 0.5, Hz)) %>%
    mutate(Distance = Distance - 28) %>%
    mutate(sum = 
             map(data,
                 calculate_mean_velocity)) %>%
    unnest(sum) %>%
    mutate(data = 
             map(data,
                 calculate_residuals)) %>%
    mutate(mean_stress = 
             map_dbl(data, 
                     calculate_mean_stress)) %>%
    mutate(mean_tke = 
             map_dbl(data, 
                     calculate_mean_tke)) %>%
    mutate(total_time = 
             map_dbl(data,
                     calculate_total_time)) %>%
    mutate(data = 
             map(data,
                 quadrant_analysis)) %>%
    mutate(data = 
             map(data, function(X) {
               X %>%
                 mutate(Event = 
                          factor(Quadrant,
                                 labels = c("Outward interaction",
                                            "Ejection",
                                            "Inward interaction",
                                            "Sweep"),
                                 order = TRUE)) %>%
                 mutate(Quadrant = 
                          factor(Quadrant,
                                 labels = c("I", "II", "III", "IV"),
                                 order = TRUE))
             })) %>%
    mutate(data = map(data, function(X) {
      X %>%
        select(-(x:z2), -w2, -w)
    })) 
}
```



```{r read_data, cache = TRUE}
# Don't read all of the data!
col_types = "nnnc_nnnnn____nnnn"
col_names = c("Hz", "Depth", "Distance", "Density",
              "tau","x", "y", "z","z2", 
              "u", "v", "w", "w2")
out = read_csv("Modified_Data/vector_all.csv", 
               col_types = col_types,
               col_names = col_names, skip = 1)
height = read_csv("Data/Exp_Height_180522.csv")
```

```{r}
quadrant_analysis = quadrant_analysis_function(0)

out %>%
  group_by(Hz, Depth, Distance, Density) %>%
  nest() %>% 
  mutate(m = map_dbl(data, function(X) {
    X %>% pull(tau) %>% max()
  }))

out2 =
  out %>%
  group_by(Hz, Depth, Distance, Density) %>%
  nest() %>% 
  mutate(data = map(data, function(X) {
    X %>% filter(tau > 2*60*200)
  })) %>% 
  run_analysis()
```



```{r}
out %>% 
  group_by(Hz, Depth, Distance, Density) %>% 
  summarise_at(vars(x:w2),
               funs(mean), na.rm=T) %>% 
  print(n = Inf)
```







```{r}
out2 = 
  out2 %>% 
  group_by(Hz, Depth, Distance, Density) %>%
  summarise(Position = first(Position),
            U = mean(u_mean),
            V = mean(v_mean),
            W = mean(w_mean),
            TKE = sum(mean_tke))
```

```{r}
out2 = left_join(out2,
          height %>% 
  mutate(Density = recode(Density, Middle = "Medium")) %>% 
  mutate(Density = factor(Density, levels = c("High", "Medium", "Low"),order =T)),
  by = c("Hz", "Density"))
```

```{r}
out2 %>% 
  ungroup() %>% 
  group_by(Density, Hz) %>% 
  mutate(Um = mean(U, na.rm=T)) %>% 
  ungroup() %>% 
  mutate(Hz = factor(Hz)) %>% 
  ggplot(aes(x = Distance/Height,
             y = U, 
             color = Position,
             group = interaction(Density, Hz, Depth))) +
  geom_point() +
  geom_line() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  scale_color_brewer(palette = "Dark2") +
  facet_rep_grid(Hz ~ Density, scale = "free_y") +
  theme(axis.line = element_line())
```


```{r}
out2 %>% 
  ungroup() %>% 
  mutate(Hz = factor(Hz)) %>% 
  filter(!str_detect(Position, "edge")) %>% 
  ggplot(aes(x = Distance/Height,
             y = V, 
             color = Density,
             linetype = Position,
             group = interaction(Density, Hz, Depth))) +
  geom_point() +
  geom_line() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  scale_color_brewer(palette = "Dark2") +
  facet_rep_grid(Hz ~ Density, scales = "free_y") +
  theme(axis.line = element_line())
```

```{r}
out2 %>% 
  ungroup() %>% 
  mutate(Hz = factor(Hz)) %>% 
  filter(!str_detect(Position, "edge")) %>% 
  ggplot(aes(x = Distance/Height,
             y = W, 
             color = Density,
             linetype = Position,
             group = interaction(Density, Hz, Depth))) +
  geom_point() +
  geom_line() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  scale_color_brewer(palette = "Dark2") +
  facet_rep_grid(Hz ~ Density, scales = "free_y") +
  theme(axis.line = element_line())
```


```{r}
cnames_vectrino=c("time", "counter", "status",
                  "xvel", "yvel", "zvel", "z2vel",
                  "amp1", "amp2", "amp3", "amp4",
                  "snr1", "snr2", "snr3", "snr4",
                  "corr1", "corr2", "corr3", "corr4")
ct = "nncnnnnnnnnnnnnnnnn"
dat = read_table("Data/Velocity/1_16_41_L_180607.dat", 
               col_types = ct,
               col_names = cnames_vectrino)
dat = dat %>% mutate(tau = 1:n())
dat %>% summarise_at(vars(xvel:z2vel), funs(mean, sd))
ggplot(dat) + geom_histogram(aes(x = xvel))

dat %>% filter(time == 0)
dat %>% filter(time == 9.99)
dat %>% pull(time) %>% range()

dat = dat %>% 
  mutate(group = tau %/% 5000) %>% 
  mutate(group = factor(group))

dat %>% group_by(group) %>% 
  summarise_at(vars(xvel, zvel), funs(mean))

ggplot(dat) + 
  geom_line(aes(x = tau, y = xvel)) +
  geom_point(aes(x = tau, y = xvel)) +
  facet_wrap("group", scale = "free_x")
  
```


```{r}
cnames_vectrino=c("time", "counter", "status",
                  "xvel", "yvel", "zvel", "z2vel",
                  "amp1", "amp2", "amp3", "amp4",
                  "snr1", "snr2", "snr3", "snr4",
                  "corr1", "corr2", "corr3", "corr4")
ct = "nncnnnnnnnnnnnnnnnn"

dat2 = read_table("Data/Velocity/1_6_41_L_180607.dat", 
               col_types = ct,
               col_names = cnames_vectrino)
dat2 %>% summarise_at(vars(xvel:z2vel), funs(mean, sd))

dat2 %>% pull(time) %>% range()
dat2 %>% filter(time == 9.990)

dat2 = dat2 %>% mutate(tau = 1:n())
dat2 = dat2 %>% mutate(X = abs(xvel - mean(xvel)))
dat2 = dat2 %>% 
  mutate(group = tau %/% 5000) %>% 
  mutate(group = factor(group))

dat2 %>% group_by(group) %>% 
  summarise_at(vars(xvel, zvel), funs(mean))

ggplot(dat2) + geom_histogram(aes(x = xvel))

ggplot(dat2) + 
  geom_line(aes(x = tau * 0.005, y = X)) +
  scale_y_continuous(limits = c(0, 0.1)) +
  facet_wrap("group", scale = "free_x")

```

```{r}
out %>% pull(Hz) %>% unique()
out %>% 
  filter(Hz == 5, Depth == 16, Distance == 41) %>% 
  group_by(Hz, Depth, Distance, Density) %>% 
  summarise_at(vars(u, v, w), funs(mean), na.rm=T)

out %>% 
  filter(Hz == 2, Depth == 16, Distance == 41) %>% 
  ggplot(aes(x = u)) +
  geom_histogram() +
  facet_wrap("Density")
```


